#pragma once

#include <stdbool.h>
#include "window.h"

typedef enum TrioKey {
TRIO_KEY_SPACE          =   32,
TRIO_KEY_APOSTROPHE     =   39,
TRIO_KEY_COMMA          =   44,
TRIO_KEY_MINUS          =   45,
TRIO_KEY_PERIOD         =   46,
TRIO_KEY_SLASH          =   47,
TRIO_KEY_0              =   48,
TRIO_KEY_1              =   49,
TRIO_KEY_2              =   50,
TRIO_KEY_3              =   51,
TRIO_KEY_4              =   52,
TRIO_KEY_5              =   53,
TRIO_KEY_6              =   54,
TRIO_KEY_7              =   55,
TRIO_KEY_8              =   56,
TRIO_KEY_9              =   57,
TRIO_KEY_SEMICOLON      =   59,
TRIO_KEY_EQUAL          =   61,
TRIO_KEY_A              =   65,
TRIO_KEY_B              =   66,
TRIO_KEY_C              =   67,
TRIO_KEY_D              =   68,
TRIO_KEY_E              =   69,
TRIO_KEY_F              =   70,
TRIO_KEY_G              =   71,
TRIO_KEY_H              =   72,
TRIO_KEY_I              =   73,
TRIO_KEY_J              =   74,
TRIO_KEY_K              =   75,
TRIO_KEY_L              =   76,
TRIO_KEY_M              =   77,
TRIO_KEY_N              =   78,
TRIO_KEY_O              =   79,
TRIO_KEY_P              =   80,
TRIO_KEY_Q              =   81,
TRIO_KEY_R              =   82,
TRIO_KEY_S              =   83,
TRIO_KEY_T              =   84,
TRIO_KEY_U              =   85,
TRIO_KEY_V              =   86,
TRIO_KEY_W              =   87,
TRIO_KEY_X              =   88,
TRIO_KEY_Y              =   89,
TRIO_KEY_Z              =   90,
TRIO_KEY_LEFT_BRACKET   =   91,
TRIO_KEY_BACKSLASH      =   92,
TRIO_KEY_RIGHT_BRACKET  =   93,
TRIO_KEY_GRAVE_ACCENT   =   96,
TRIO_KEY_WORLD_1        =   161,
TRIO_KEY_WORLD_2        =   162,
TRIO_KEY_ESCAPE         =   256,
TRIO_KEY_ENTER          =   257,
TRIO_KEY_TAB            =   258,
TRIO_KEY_BACKSPACE      =   259,
TRIO_KEY_INSERT         =   260,
TRIO_KEY_DELETE         =   261,
TRIO_KEY_RIGHT          =   262,
TRIO_KEY_LEFT           =   263,
TRIO_KEY_DOWN           =   264,
TRIO_KEY_UP             =   265,
TRIO_KEY_PAGE_UP        =   266,
TRIO_KEY_PAGE_DOWN      =   267,
TRIO_KEY_HOME           =   268,
TRIO_KEY_END            =   269,
TRIO_KEY_CAPS_LOCK      =   280,
TRIO_KEY_SCROLL_LOCK    =   281,
TRIO_KEY_NUM_LOCK       =   282,
TRIO_KEY_PRINT_SCREEN   =   283,
TRIO_KEY_PAUSE          =   284,
TRIO_KEY_F1             =   290,
TRIO_KEY_F2             =   291,
TRIO_KEY_F3             =   292,
TRIO_KEY_F4             =   293,
TRIO_KEY_F5             =   294,
TRIO_KEY_F6             =   295,
TRIO_KEY_F7             =   296,
TRIO_KEY_F8             =   297,
TRIO_KEY_F9             =   298,
TRIO_KEY_F10            =   299,
TRIO_KEY_F11            =   300,
TRIO_KEY_F12            =   301,
TRIO_KEY_F13            =   302,
TRIO_KEY_F14            =   303,
TRIO_KEY_F15            =   304,
TRIO_KEY_F16            =   305,
TRIO_KEY_F17            =   306,
TRIO_KEY_F18            =   307,
TRIO_KEY_F19            =   308,
TRIO_KEY_F20            =   309,
TRIO_KEY_F21            =   310,
TRIO_KEY_F22            =   311,
TRIO_KEY_F23            =   312,
TRIO_KEY_F24            =   313,
TRIO_KEY_F25            =   314,
TRIO_KEY_KP_0           =   320,
TRIO_KEY_KP_1           =   321,
TRIO_KEY_KP_2           =   322,
TRIO_KEY_KP_3           =   323,
TRIO_KEY_KP_4           =   324,
TRIO_KEY_KP_5           =   325,
TRIO_KEY_KP_6           =   326,
TRIO_KEY_KP_7           =   327,
TRIO_KEY_KP_8           =   328,
TRIO_KEY_KP_9           =   329,
TRIO_KEY_KP_DECIMAL     =   330,
TRIO_KEY_KP_DIVIDE      =   331,
TRIO_KEY_KP_MULTIPLY    =   332,
TRIO_KEY_KP_SUBTRACT    =   333,
TRIO_KEY_KP_ADD         =   334,
TRIO_KEY_KP_ENTER       =   335,
TRIO_KEY_KP_EQUAL       =   336,
TRIO_KEY_LEFT_SHIFT     =   340,
TRIO_KEY_LEFT_CONTROL   =   341,
TRIO_KEY_LEFT_ALT       =   342,
TRIO_KEY_LEFT_SUPER     =   343,
TRIO_KEY_RIGHT_SHIFT    =   344,
TRIO_KEY_RIGHT_CONTROL  =   345,
TRIO_KEY_RIGHT_ALT      =   346,
TRIO_KEY_RIGHT_SUPER    =   347,
TRIO_KEY_MENU           =   348,
} TrioKey;

#ifdef __cplusplus
extern "C" {
#endif

void TrioPollEvents();
bool TrioIsKeyPressed(TrioWindow* window, TrioKey key);

#ifdef __cplusplus
}
#endif